name: Build lkm with SUSFS

on:
    workflow_dispatch:
        inputs:
              KernelSU_repo:
                required: true
                type: choice
                description: >
                    Repo of KernelSU
                options:
                    - tiann/KernelSU
                    - 5ec1cff/KernelSU
                    - rifsxd/KernelSU-Next
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 226
            os_patch_level: 2024-11
          - version: "android13-5.10"
            sub_level: 223
            os_patch_level: 2024-11
          - version: "android13-5.15"
            sub_level: 167
            os_patch_level: 2024-11
          - version: "android14-5.15"
            sub_level: 167
            os_patch_level: 2024-11
          - version: "android14-6.1"
            sub_level: 115
            os_patch_level: 2024-12
          - version: "android15-6.6"
            sub_level: 57
            os_patch_level: 2024-12
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      KernelSU_repo: ${{ inputs.KernelSU_repo }}
      build_lkm: true
